### ISSUE TITLE
PERSON: PDF-Download Paddle Level / Paddle Star

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_skv#10]
Auf der Personenseite kann der Benutzer seinen Paddle-Star-Ausweis als PDF herunterladen.
Leute mit Schreibrecht auf die Person, können den Paddle-Star-Ausweis herunterladen.

Das Paddle-Level ist ein Nachweis des Könnens des Benutzers. Es basiert auf dem EPP (European Paddle Level)

* Boolean Flag auf Qualifikationsart ergänzen: Erscheint auf Paddle Pass (ja/nein)

Auf der Personenseite kann der Benutzer sein Paddle-Level Ausweis als PDF herunterladen.

PDF mit folgenden Informationen:
* Logo & Adresse Swiss Canoe
* Vorname/Name
* Sektion: lokaler Kanuclub (Primary Group, oder von einer beliebigen Rolle falls keine Primary Group)
  * Shortname
  * Fallback auf Name
* Paddle Level (1-5) --> Nur Qualifikationen anzeigen die das oben beschriebene Flag gesetzt haben. (Bsp aus der Praxis: SUP, Whitewater Kajak, Touring)
  * Datum der Erfassung der Qualifikation, falls dies nicht zu kompliziert ist.
  * Qualifikationen auf der Person
* hinweis auf EPP (based on European Paddle Pass): based on the Euro Paddle Pass Standard, www.europaddlepass.eu
* EPP-Logo
  * [x] THI liefet das logo
* [x] Layout senkrecht statt quer (THI klärt ab)
![epp](https://user-images.githubusercontent.com/17568539/144059797-d7018eef-fb35-4643-a184-52c6b8f0c8d1.png)

![paddle-stars](https://user-images.githubusercontent.com/17568539/146358321-1034e5ad-4df5-4b05-a830-775e866c6b0c.png)

Die Assessors vorerst noch nicht umsetzen. Diese wird wohl auf bestimmten Rollen basieren.

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito_skv/tree/feature/skv_10_paddle_id

TODO
- [ ] Naming `appears_on_paddle_pass` nochmal überdenken. (`paddle_pass_relevant` ?)
- [ ] `appears_on_paddle_pass` in qualification_kinds list anzeigen?
- [ ] PDF Layouting muss sicher noch verfeinert werden
- [ ] EPP Logo im PDF
- [ ] Button auf Profil
- [ ] Export Specs

**Comment by severinraez** [comment]
TODO: Rebase auf master für neue Features
