### ISSUE TITLE
PEOPLE: Verifikation des Mitgliederausweises

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_skv#11]
Hinter einer versteckten (hashed) URL, welche durch einen QR-Code zugänglich ist, ist ein verstecktes Mini-Profil eines Mitgliedes zugänglich, welches folgende Infos enthält:

- Logo Swiss Canoe
- Vorname Name
- Foto, falls vorhanden
- Hinweis, ob es sich um ein verifiziertes Mitglied handelt
  - grünes Gutzeichen, falls in DB und Mitglied
  - rotes Kreuz, falls in DB aber keine Rollen oder Rolle "externer Kontakt" (Rolle mit kind extern)
- Zugriff auf diese Seite ist anhand Unique ID ohne Login/Session (devise) möglich
- Seite ist auf Mobile optimiert, Navigation wird grundsätzlich nicht benötigt (Standalone page)

# Tech Spec
- Umsetzung im skv-Wagon
- Neues Feld auf der Person welches einen zufälligen, unique String enthält
- Neuer Controller der es erlaubt, das "Mini-Profil" der Person anzuzeigen
- Sollte unter einer Route erreichbar sein die nur den random String enthält, keine Gruppen- oder Personen-Ids

**Comment by TheWalkingLeek** [comment]
#22
