### ISSUE TITLE
Grundpaket: Produktionsumgebung

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_skv#4]
# Vorbereitung der produktiven Umgebung

- [x] composition-repo um production-branch erweitern
- [x] APPUiO-Projekt anlegen
- [x] labels setzen
- [x] initial-setup mit [cia](https://wiki.puzzle.ch/Hitobito/ProjektSetup)
- [x] kustomize-overlay
- [x] apply-config
- [x] jenkins-job
- [x] Credentials im Cryptopus
	- [x] secret-key-base
	- [x] root-user
- [x] manueller Adress-Import: `bundle exec rake address:import`
/2681)
- [x] [Rechnungsbriefe aktivieren](https://github.com/hitobito/hitobito_sbv/pull/107/files#diff-e769bbb8c1ba3711c5403b424ed9c218ffafba7f1890ee394717196f28ff4540R40)
- [x] [Monitoring](https://docs.puzzle.ch/guides/latest/ruby-rails-user-guide/index.html#_monitoring_einrichten)
	- [x] ServiceMonitor "freischalten lassen" und einrichten
	- [x] [PR](https://gitlab.puzzle.ch/pitc_ansible/ansible-puzzle/-/merge_requests) für Blackbox-Checks
- [x] mailkonten Verifikation
- [x] DNS: db.swisscanoe.ch
	- [x] Kunden informieren
	- [ ] Verifikation
	- [x] [PR für Mailsserver](https://gitlab.puzzle.ch/pitc_ansible/ansible-puzzle/-/merge_requests/2747)

See: #1

**Comment by kronn** [comment]
@chrusu der SKV kann informiert werden, dass DNS eingerichtet werden kann, siehe https://wiki.puzzle.ch/Hitobito/ProjektSetup#DNS_Einstellungen_Kundenseite
