### ISSUE TITLE
Grundpaket: Mehrsprachigkeit

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_skv#8]
Gewünschte Sprachen DE, FR einbauen

- [x]  settings.yml
- [x]  transifex -> eigenes Projekt (für Wagon spezifische Übersetzungen)
- [x]  model.yml erstellen und ins transifex pushen

See: #1

**Comment by olibrian** [comment]
Da ist wohl noch was nicht ganz korrekt:
![image](https://user-images.githubusercontent.com/9592347/143544112-31b95e6a-215e-45c7-af7e-a6fbe2a4cc05.png)

**Comment by mtnstar** [comment]
> Da ist wohl noch was nicht ganz korrekt: ![image](https://user-images.githubusercontent.com/9592347/143544112-31b95e6a-215e-45c7-af7e-a6fbe2a4cc05.png)

oh merci! copy paste fehler ... habs gefixt

**Comment by olibrian** [comment]
Transifex unterstützt Open Source Projekte. Damit dies auch entsprechend aufgenommen wird, habe ich noch die Settings unter https://www.transifex.com/hitobito/hitobito_skv/settings/ korrekt gesetzt.
